name: homefindr
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^3.0.3

  # Dependency Injection
  get_it: ^9.2.0

  # Responsive Layout
  responsive_builder: ^0.7.1

  # Routing & Navigation
  go_router: ^17.0.0

  # UI, Styling & Assets
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  animated_text_kit: ^4.3.0

  # Animations
  flutter_animate: ^4.5.2
  lottie: ^3.3.2

  # Utilities
  intl: any
  url_launcher: ^6.3.2
  logger: ^2.6.2
  visibility_detector: ^0.4.0+2
  scrollable_positioned_list: ^0.3.8
  web: ^1.1.1

  # Firebase & Backend
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_analytics: ^12.0.4


  # Connectivity & Platform
  connectivity_plus: ^7.0.0


  # Data Modeling & Equality
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0


  # Additional necessary dependencies
  google_maps_flutter: ^2.9.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.3.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.1
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
